/***************************  MENU ITEMS - APPLICATIONS  ***************************/

const uiElements = {
  id: "group-ui-elements",
  title: "Finance",
  icon: "Home",
  type: "group",
  roles: ["Admin", "PlatformOwner"],
  children: [
    {
      id: "components",
      title: "Chart of Accounts",
      type: "item",
      icon: "AccountBalanceWallet",
      url: "/admin-panel/accounts",
      roles: ["Admin", "PlatformOwner"],
    },
    {
      id: "components",
      title: "Accounts payable",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/transactions",
      roles: [],
    },
    {
      id: "components",
      title: "Accounts Payable",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/accounts-payable",
      roles: [],
    },
    {
      id: "components",
      title: "Accounts Receivable",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/accounts-receivable",
      roles: ["Admin", "PlatformOwner"],
    },
    {
      id: "components",
      title: "Discounts",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/discounts",
      roles: ["Admin", "PlatformOwner"],
    },
    {
      id: "components",
      title: "Exceptions",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/exemptions",
      roles: ["Admin", "PlatformOwner"],
    },
    {
      id: "components",
      title: "Invoices",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/invoices",
      roles: ["Admin", "PlatformOwner"],
    },
    {
      id: "components",
      title: "Transactions",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/transactions",
      roles: [],
    },
    {
      id: "components",
      title: "Payment Methods",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/payment-methods",
      roles: ["Admin", "PlatformOwner"],
    },
    {
      id: "components",
      title: "Payment Aggregators",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/payment-aggregators",
      roles: ["Admin", "PlatformOwner"],
    },
    {
      id: "components",
      title: "Payments",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/payments",
      roles: [],
    },
    {
      id: "components",
      title: "Payment Plans",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/payment-plans",
      roles: ["Admin", "PlatformOwner"],
    },
    {
      id: "components",
      title: "Payment Notifications",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/payment-notifications",
      roles: ["Admin", "PlatformOwner"],
    },
    {
      id: "components",
      title: "Customer Plans",
      type: "item",
      icon: "Badge",
      url: "/admin-panel/customer-plans",
      roles: ["Admin", "PlatformOwner"],
    },
  ],
};

export default uiElements;
